# Inspired from https://github.com/fgiloux/auto-perf-test/blob/master/jmeter/container/Dockerfile
FROM registry.access.redhat.com/ubi8/openjdk-11
MAINTAINER Renato Felix<rfelix@redhat.com>

ENV JMETER_VERSION "5.5"
ENV AMQ_VERSION "7.10.1"

LABEL jmeter.version=${JMETER_VERSION}
LABEL amq.version=${AMQ_VERSION}

# Set JMeter base and home
ENV OPT_BASE /opt
ENV JMETER_BASE /opt/jmeter
ENV JMETER_HOME $JMETER_BASE/apache-jmeter-${JMETER_VERSION}

ENV AMQ_BASE /opt/amq
ENV AMQ_HOME $AMQ_BASE/amq-broker-${AMQ_VERSION}


# Add JMeter to the Path
ENV PATH $JMETER_HOME/bin:$AMQ_HOME/bin:$PATH

# Create jmeter directory with tests and results folder and install JMeter
RUN mkdir -p $JMETER_BASE/{tests,results} \
 && mkdir -p $AMQ_BASE/

# Option 1: Download latest jmeter binaries from the Apache archive:
#RUN curl -SL https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-${JMETER_VERSION}.zip -o apache-jmeter-${JMETER_VERSION}.zip \
#    && cd $JMETER_BASE ; unzip ~/apache-jmeter-${JMETER_VERSION}.zip \
#    && rm -rf apache-jmeter-${JMETER_VERSION}.zip

# Option 2: If you don't have internet access from the build machine use COPY instead of curl.
# In this case, you will need the binaries in the same folder as this Dockerfile.
RUN mkdir -p $JMETER_HOME
COPY apache-jmeter-${JMETER_VERSION} $JMETER_HOME

COPY amq-broker-${AMQ_VERSION} $AMQ_HOME
# RUN tar -xf $JMETER_BASE/apache-jmeter-${JMETER_VERSION}.tgz -C $JMETER_BASE \
#     && rm -rf $JMETER_BASE/apache-jmeter-${JMETER_VERSION}.tgz

############# ARE PLUGINS NEEDED?
# COPY binaries/JMeterPlugins-ExtrasLibs-1.4.0.zip $JMETER_BASE/apache-jmeter-${JMETER_VERSION}/

# Set working directory
WORKDIR $JMETER_BASE

USER 0

RUN chown -R 1001:root $OPT_BASE \
    && chmod -R g+rwx,o+x $OPT_BASE

#1001 is an arbitrary choice
USER 1001
